# Generated by Django 5.0.6 on 2024-06-30 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_company_rename_name_account_full_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
