# Generated by Django 5.0.6 on 2024-06-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_account_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
    ]
