# Generated by Django 5.0.6 on 2024-07-01 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_employee_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_id',
            field=models.BigAutoField(primary_key=True, serialize=False, unique=True),
        ),
    ]
