# Generated by Django 5.0.6 on 2024-07-03 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_employee_salary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company_id',
        ),
    ]
