# Generated by Django 5.0.6 on 2024-07-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_employee_username_owner_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
