# Generated by Django 5.0.6 on 2024-07-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_owner_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='username',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
    ]
